// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs810U4UyX0zoxKmTBQQceKE4U8wrYo58',
    appId: '1:1097414341020:web:692068a38ad00eb0989859',
    messagingSenderId: '1097414341020',
    projectId: 'drb-final',
    authDomain: 'drb-final.firebaseapp.com',
    storageBucket: 'drb-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8FjCjgQt7c_4jD2JsqiLHJxWRhegIq2Y',
    appId: '1:1097414341020:android:37efac220d1c4fa9989859',
    messagingSenderId: '1097414341020',
    projectId: 'drb-final',
    storageBucket: 'drb-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-UNHKP7gr9UlKMUgqIV8kdpW1SQuW3zc',
    appId: '1:1097414341020:ios:706ca3b5d8385e7b989859',
    messagingSenderId: '1097414341020',
    projectId: 'drb-final',
    storageBucket: 'drb-final.appspot.com',
    iosClientId: '1097414341020-u1dkaqcteua96a78n38n7i8n4rt62han.apps.googleusercontent.com',
    iosBundleId: 'com.example.drbApp',
  );
}
